name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    timeout-minutes: 45  # Increase timeout to 45 minutes
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true  # Enable debug logs for better visibility

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ensure correct Node.js version for your project

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v2  # Use the latest version for improvements
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_DESERT_00B0C4A0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          
          ###### Repository/Build Configurations ######
          app_location: "./blog/"  # Ensure this path is correct for your app
          api_location: ""  # Leave empty if no API is used
          output_location: ""  # Optional, specify if necessary
          ###### End of Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job

    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v2
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_DESERT_00B0C4A0F }}
          action: "close"
